### ISSUE TITLE
프로젝트 주제 선정

### ISSUE THREAD

**Issue by zave7** [team-sesac/credit-card-churn-predictor.t3#2]
주제 : 신용카드 고객 이탈률 예측 및 고객 이탈 방지 분석

비즈니스 모델 구상 : 비용 시나리오를 세워서 최적화 된 모델을 선정해내는 방법으로 접근 (confusion matrix)
(이탈하는 고객을 막는 비용보다 신규 고객을 확보하는 비용이 8배 가량 많음)

**Comment by statezeropy** [comment]
신용카드 고객이탈률예측

**Comment by seyeon-shijuan** [comment]
신용카드 이탈 고객 분석 및 이탈율 예측

**Comment by zave7** [comment]
고객 분석을 바탕으로 비즈니스 인사이트 도출

**Comment by zave7** [comment]
가설을 기반으로 가장 성능이 좋은 모델 결과로 고객들을 군집화 하여 각 고객군의 특성을 파악하고 비즈니스 전략을 세울 수 있도록 진행해보자.
@KimJuyoung23 @seyeon-shijuan @JangMinJung
