### ISSUE TITLE
데이터 전처리 및 시각화

### ISSUE THREAD

**Issue by zave7** [team-sesac/credit-card-churn-predictor.t3#5]
1. 전처리는 이상치 제거는 없음
2. 카테고리 결측치 knn
3. 범주형 one-hot 인코딩
4. standard 스케일링

**Comment by zave7** [comment]
c6fc1d24f3abe358206ba72e660394fc00d61331

**Comment by statezeropy** [comment]
필사 느낌으로 진행하여 참고한 캐글 링크 공유드립니다.

- 참고 캐글1
-- 반복문으로 전체 데이터 그리는 방법이 인상 깊었음
https://www.kaggle.com/code/sonalisingh1411/customer-churn-eda-top-5-models-95?scriptVersionId=87844451&cellId=37 
-- 응용 : fig = ex.histogram(df, x=feature, title=f'Distribution of {feature}', pattern_shape='Attrition_Flag', barmode='group')
-- 나이를 그룹으로 변경하여 분석.
https://www.kaggle.com/code/sonalisingh1411/customer-churn-eda-top-5-models-95?scriptVersionId=87844451&cellId=48 
-- 그외 모델 학습, 하이퍼파라미터, 컨퓨전메트릭스 정리까지 정리됨.

- 참고 캐글2
-- 한눈에 보는 시각화?. 마무리에 컨퓨전메트릭스 완성.
https://www.kaggle.com/code/vivek468/will-the-customer-churn?scriptVersionId=87888629&cellId=14

- 참고 캐글3
-- 단순히 pie로 그린 예시
https://www.kaggle.com/code/harbaldeepsidhu/credit-card-customers-analysis?scriptVersionId=117654490&cellId=33

**Comment by zave7** [comment]
전처리 및 시각화 커밋..
6abdf431bf91ea77c211ea9ecebc54c1569fc259

**Comment by seyeon-shijuan** [comment]
2023-10-30 작업내역

- 분포도 분석 (stacked bar chart, histogram(
- 다중공선성 제거 1건(Credit_Limit 과 Avg_Open_To_Buy에서 open to buy 제거)
- categorical variales 라벨 인코딩
- Unknown 값 KNN으로 결측치 대체

Ref.
https://www.kaggle.com/code/yogidsba/credit-card-churn-regularization-ensemble
https://www.kaggle.com/code/sonalisingh1411/customer-churn-eda-top-5-models-95
