### ISSUE TITLE
데이터 전처리 및 시각화 리뷰

### ISSUE THREAD

**Issue by zave7** [team-sesac/credit-card-churn-predictor.t3#6]
Due : 10/31 11:00

**Comment by statezeropy** [comment]
# 리뷰 내용 정리

- [x] 데이터 전처리
 - 결측값은 KNN
 - 이상치제거 없음
 - 라벨인코딩, 원핫인코딩(성별, 결혼상태)
 - standard scaling
 - 나이는 범주화하지 않기

- [ ] autoML
- [ ] Data 시각화, 분석
- [ ] hyper parameter 튜닝

**Comment by seyeon-shijuan** [comment]
베이스 데이터 셋

preprosessing_script_sy.py
https://github.com/team-sesac/credit-card-churn-predictor.t3/blob/main/src/EDA/preprosessing_script_sy.py
파이썬 파일
실행하면 바로 피클 파일로 만들 수 있음
나중에 변환 데이터셋 만들 때 사용 가능

preprocessing_sy.ipynb
https://github.com/team-sesac/credit-card-churn-predictor.t3/blob/main/src/EDA/preprocessing_sy.ipynb
노트북 파일
전처리 전체 원본 파일

base_dataset_standardized.pkl
https://github.com/team-sesac/credit-card-churn-predictor.t3/blob/main/data/base_dataset_standardized.pkl
파이썬 판다스 데이터프레임 객체 저장한 파일
아래 명령어로 바로 불러올 수 있음

import pandas as pd
DATA_DIR = "../../data/"
test = pd.read_pickle(DATA_DIR + 'base_dataset_standardized.pkl')

base_dataset_before_std.pkl
https://github.com/team-sesac/credit-card-churn-predictor.t3/blob/main/data/base_dataset_before_std.pkl
정규화 이전의 원본 값 데이터
